In [3]:
import numpy as np

In [4]:
#Using array method
#1d array
virat_runs = np.array([72,45, 88,101])
print("1d array")
print(virat_runs)

#2d array
team_runs = np.array([[72,45, 88],  #virat
                      [55,60,47],  #rohit
                      [30,75,50]]) #dhoni
print("\n2d array")
print(team_runs)

1d array
[ 72  45  88 101]

2d array
[[72 45 88]
 [55 60 47]
 [30 75 50]]


In [5]:
#Using array method from tuple
player_ages = np.array((35,37,31))
print(player_ages)

[35 37 31]


In [6]:
#Special arrays
zeros = np.zeros((2,3))
ones = np.ones((3,2))
identity = np.eye(3)
print(zeros)
print()
print(ones)
print()
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
empty = np.empty((2,2))
print()
print(empty)

full = np.full((2,2),7)
print()
print(full)


[[0.0000000e+000 1.2487751e-311]
 [1.2487751e-311 1.2487751e-311]]

[[7 7]
 [7 7]]


In [8]:
arr = np.arange(55,65)
print(arr)
arr[4] = 1000

print(arr)

[55 56 57 58 59 60 61 62 63 64]
[  55   56   57   58 1000   60   61   62   63   64]


In [9]:
run_rates = np.arange(4,11,1)
print(run_rates)

run_rates = np.arange(4,11,2)
print(run_rates)

[ 4  5  6  7  8  9 10]
[ 4  6  8 10]


In [10]:
#arange vs linspace

arr1 = np.arange(4,11,1)
arr2 = np.linspace(2,10,5)

print(arr1)
print(arr2)

[ 4  5  6  7  8  9 10]
[ 2.  4.  6.  8. 10.]


In [11]:
rand_nums = np.random.uniform(100,200,10)
rand_nums

array([152.49110177, 166.08578479, 187.7568396 , 196.82240744,
       131.87864831, 142.35058909, 127.89538811, 159.3478838 ,
       156.50562608, 132.28217374])

In [12]:
rand_nums2 = np.random.randint(1,151,(2,3))
rand_nums2

array([[ 95, 143,  98],
       [ 57, 130,  34]], dtype=int32)

In [13]:
rand_nums3 = np.random.normal(40,5,(2,3))
rand_nums3

array([[40.82085319, 34.21776844, 43.82340943],
       [36.03271598, 33.20712249, 43.35074264]])

In [14]:
arr_modified = np.append(arr,1100)
arr_modified

array([  55,   56,   57,   58, 1000,   60,   61,   62,   63,   64, 1100])

In [15]:
arr_modified2 = np.append(arr,[1,2,3,4,5,6,7])
arr_modified

array([  55,   56,   57,   58, 1000,   60,   61,   62,   63,   64, 1100])

In [16]:
marks = np.arange(50, 62)
print(marks)
print()
reshaped_marks = marks.reshape(3,4)
print(reshaped_marks)

[50 51 52 53 54 55 56 57 58 59 60 61]

[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]]


In [17]:
marks = np.array([55,67,45,70,89,90,76,88,95,100])
print(marks)

print(marks[8])
print(marks[1:5])
print(marks[0:5])

[ 55  67  45  70  89  90  76  88  95 100]
95
[67 45 70 89]
[55 67 45 70 89]


In [18]:

result = marks + 5
print(result)

[ 60  72  50  75  94  95  81  93 100 105]


In [19]:
top_batch = marks[0:3]
print(top_batch)
print(marks)
top_batch[0:3] = 100
print(marks)
print(top_batch)

[55 67 45]
[ 55  67  45  70  89  90  76  88  95 100]
[100 100 100  70  89  90  76  88  95 100]
[100 100 100]


In [22]:
#conditional selection
marks = np.array([55,67,45,70,89,90,76,88,95,100])
print(marks)

passed = marks > 80
print(passed)
print(marks[passed])

# or 

print(marks[marks>80])

[ 55  67  45  70  89  90  76  88  95 100]
[False False False False  True  True False  True  True  True]
[ 89  90  88  95 100]
[ 89  90  88  95 100]


In [29]:
arr = np.arange(1,10)
print(arr + arr)
print(arr * arr)
print(arr - arr)
print(arr / arr)
print(arr ** arr)
print(arr ** 3)
print(np.sqrt(arr))

[ 2  4  6  8 10 12 14 16 18]
[ 1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  1   8  27  64 125 216 343 512 729]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [28]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [27]:
#conditional selection
marks = np.array([55,67,45,70,89,90,76,88,95,100])
print(marks)

passed = marks > 80
print(passed)
print(marks[passed])

# or 

print(marks[marks>80])

[ 55  67  45  70  89  90  76  88  95 100]
[False False False False  True  True False  True  True  True]
[ 89  90  88  95 100]
[ 89  90  88  95 100]


In [31]:
sorted_marks = np.sort(marks)
print(sorted_marks)

sorted_marks = np.sort(marks)[::-1]
print(sorted_marks)

[ 45  55  67  70  76  88  89  90  95 100]
[100  95  90  89  88  76  70  67  55  45]


In [32]:
students = np.array([('Alice', 85, 20),
                     ('Bob', 88, 21),
                     ('Charlie', 92, 19)],
                     dtype = [('name','U10'), ('marks', 'i4'), ('age', 'i4')])
students

array([('Alice', 85, 20), ('Bob', 88, 21), ('Charlie', 92, 19)],
      dtype=[('name', '<U10'), ('marks', '<i4'), ('age', '<i4')])

In [37]:
print(students['name'])
print(students['age'])
print(students['marks'])
print(students['marks'].mean())
print(students[students['name'] == 'Bob']['marks'])
print(students[students['name'] == 'Bob']['marks'][0])

['Alice' 'Bob' 'Charlie']
[20 21 19]
[85 88 92]
88.33333333333333
[88]
88


In [39]:
sales = [0,5,155,0,518, 616]
sales_array = np.array(sales)

print(type(sales_array))
print(sales_array.ndim)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.dtype)

<class 'numpy.ndarray'>
1
(6,)
6
int64


In [40]:
result_array = np.where(sales_array == 0, "No Sales", "Some sales")
print(result_array)

['No Sales' 'Some sales' 'Some sales' 'No Sales' 'Some sales' 'Some sales']


In [42]:
bool_mask = sales_array!= 0
print(bool_mask)

filtered_sales = sales_array[bool_mask]
print(filtered_sales)

[False  True  True False  True  True]
[  5 155 518 616]
