In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)

[11 22 33]


In [5]:
s1 = pd.Series([10,20,30,40], index = ['x','y','z','a'])
s2 = pd.Series([1,2,3], index = ['y','z','x'])
print(s1+s2)

a     NaN
x    13.0
y    21.0
z    32.0
dtype: float64


Creating a PD Series

In [ ]:
# M-1
names = ['Alice', 'Bob', 'Charlie']
marks = [67,31,81]

stu = pd.Series(data = marks)
print(stu)

stu = pd.Series(data = marks, index = names)
print(stu)

0    67
1    31
2    81
dtype: int64
Alice      67
Bob        31
Charlie    81
dtype: int64


In [ ]:
# M-2
random_ages = np.random.randint(0,100,4)
names.append('David')
people_arr = pd.Series(data = random_ages, index = names)
print(people_arr)

Alice      25
Bob        24
Charlie    49
David      40
dtype: int32


In [9]:
# M-3
names_ages_dict = {'Alice':21, 'Bob':25, 'Charlie':19, 'David':23}
print(pd.Series(names_ages_dict))

Alice      21
Bob        25
Charlie    19
David      23
dtype: int64


In [15]:
#Creting imaginary sales data for quater 1 and quater 2
q1 = {'Japan':80, 'China':450, 'India':200, 'USA':250, 'Mexico':150}
q2 = {'Japan':100, 'China':550, 'India':210, 'USA':260}

sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

print(sales_q1)
print(sales_q1['Japan'])
print(sales_q2[0])

Japan      80
China     450
India     200
USA       250
Mexico    150
dtype: int64
80
100


C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_6328\1920342658.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sales_q2[0])


In [16]:
print(sales_q1.keys())
print(sales_q1*2)
print(sales_q2 / 100)

Index(['Japan', 'China', 'India', 'USA', 'Mexico'], dtype='object')
Japan     160
China     900
India     400
USA       500
Mexico    300
dtype: int64
Japan    1.0
China    5.5
India    2.1
USA      2.6
dtype: float64


In [17]:
#Handling missing values in pd

print(sales_q1 + sales_q2)
sales_q1.add(sales_q2, fill_value=0)

China     1000.0
India      410.0
Japan      180.0
Mexico       NaN
USA        510.0
dtype: float64


China     1000.0
India      410.0
Japan      180.0
Mexico     150.0
USA        510.0
dtype: float64

In [18]:
#Creating a pd dataframe

scores = np.random.randint(0,101, (4,3)) #4players 3 matches
print(scores)

players = ['Virat', 'Rohit', 'Dhoni', 'Jadeja'] #index
matches = ['match1', 'match2', 'match3'] #3columns

df = pd.DataFrame(data=scores)
print(df)

[[50 73 81]
 [69 99 87]
 [ 0 44 45]
 [75 98 70]]
    0   1   2
0  50  73  81
1  69  99  87
2   0  44  45
3  75  98  70


In [19]:
df = pd.DataFrame(data = scores, index = players)
print(df)

         0   1   2
Virat   50  73  81
Rohit   69  99  87
Dhoni    0  44  45
Jadeja  75  98  70


In [28]:
df = pd.DataFrame(data = scores, index = players, columns = matches)
print(df)

        match1  match2  match3
Virat       50      73      81
Rohit       69      99      87
Dhoni        0      44      45
Jadeja      75      98      70


In [29]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Virat to Jadeja
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   match1  4 non-null      int32
 1   match2  4 non-null      int32
 2   match3  4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes
None


In [30]:
print(df.loc['Virat'])

match1    50
match2    73
match3    81
Name: Virat, dtype: int32


In [31]:
print(df.loc[['Virat', 'Rohit']])

       match1  match2  match3
Virat      50      73      81
Rohit      69      99      87


In [34]:
print(df.loc['Virat','match2'])

73


In [37]:
print(df)
print()

print(df.iloc[0])
print()

print(df.iloc[0:2])
print()

print(df.iloc[0,1])
print()

        match1  match2  match3
Virat       50      73      81
Rohit       69      99      87
Dhoni        0      44      45
Jadeja      75      98      70

match1    50
match2    73
match3    81
Name: Virat, dtype: int32

       match1  match2  match3
Virat      50      73      81
Rohit      69      99      87

73

